### ISSUE TITLE
Possible error in course materials - should this go here?

### ISSUE THREAD

**Issue by carolbooth2** [Newcastle-University-HPC/CarpentriesWorkshops#7]
https://nclrse-training.github.io/git-novice/05-history/index.html#:~:text=%24%20echo%20%22ketchup%20enchances%20pasta%20dishes%22%20%3E%20ketchup.md

Above link to a line In section "Understanding Workflow and History"
I believe the higlighted command should have >> to append rather than > which will replace the file content

**Comment by jsteyn** [comment]
I have deleted the git-novice repository because we are using the git-ultra-novice version of the lesson.

With regards to the error it doesn't really matter whether > or >> is used as the question "What is the output of the last command?" will be the same. Changes after the add command will not reflect in the checked out file because if it wasn't added (staged), it was never committed.
