### ISSUE TITLE
Audience Interaction - Uni supported system - should we use Clapr or Vevox?

### ISSUE THREAD

**Issue by carolbooth2** [Newcastle-University-HPC/CarpentriesWorkshops#8]
WORKSHOPS & TRAINING

Vevox Online Workshops
Vevox is Newcastle University's centrally-supported Audience Interaction System, and allows colleagues to conduct live polls, quizzes and surveys with students. We are running a number of Vevox sessions over the summer:

[Getting started with Vevox Audience Interaction System](https://elements.ncl.ac.uk/course/view.php?id=2200)
31 July 2024 10:00-11:00
12 August 2024, 14:00-15:00
30 August 2024, 11:00-12:00
10 September 2024,15:00-16:00
25 September 2024,10:00-11:00

[Vevox Audience Interaction System – advanced features webinar](https://elements.ncl.ac.uk/course/view.php?id=2341)
5 August 2024, 15:00-16:00
4 September 2024, 10:00-11:00
19 September 2024, 15:00-16:00
2 October 2024, 10:00-11:00

If you are interested in seeing the latest developments to Vevox and product roadmap plans, the [recording of the latest Vevox Seasonal Round Up Webinar is now available](https://www.youtube.com/watch?v=-PAv2qyTHRY).

**Comment by carolbooth2** [comment]
https://help.vevox.com/hc/en-us/articles/360002381098-Embedding-Vevox-as-an-iframe-in-webpages-or-other-event-apps

**Comment by jsteyn** [comment]
I think when it comes to Carpentries workshops we should avoid university specific tools because it can't be share outside the organisation. 

Also:

1. We have already started using it and I don't want to have to learn yet another application.
2. Claper is open source and can be hosted by oneself.
3. The hosted version is free for up to 25 people which is enough for most of our workshops.
4. The cost is very low when upgrading and I'd rather support an open source application than a proprietary one.
